#!/usr/bin/env bash
set -euo pipefail

# Move to project root
cd "$(dirname "$0")/.."

echo "Running ruff check..."
uv run ruff check . --fix

echo "Running mypy..."
uv run mypy

echo "Running tests..."
uv run pytest
